import { v4 as uuid } from 'uuid'; import { db } from '../db/client';
import { unitsOfMeasure, materialCategories, materialCatalog, equipmentTypes, skillCatalog } from '../db/schema';
import { eq } from 'drizzle-orm';

export const uomService = { create(params: { companyId: string; code: string; name: string; category?: string; baseUnitId?: string; conversionFactor?: number }) { return db.insert(unitsOfMeasure).values({ id: uuid(), companyId: params.companyId, code: params.code, name: params.name, category: params.category||null, baseUnitId: params.baseUnitId||null, conversionFactor: params.conversionFactor||1 }).returning().get(); }, convert(quantity: number, fromId: string, toId: string) { const f=db.select().from(unitsOfMeasure).where(eq(unitsOfMeasure.id, fromId)).get(), t=db.select().from(unitsOfMeasure).where(eq(unitsOfMeasure.id, toId)).get(); if(!f||!t) return null; return (quantity*f.conversionFactor)/t.conversionFactor; } };
export const materialCategoryService = { create(params: { companyId: string; categoryCode: string; categoryName: string; parentId?: string }) { return db.insert(materialCategories).values({ id: uuid(), companyId: params.companyId, categoryCode: params.categoryCode, categoryName: params.categoryName, parentId: params.parentId||null }).returning().get(); } };
export const materialCatalogService = { create(params: { companyId: string; materialCode: string; materialName: string; categoryId?: string; uomId?: string; description?: string; standardRate?: number }) { return db.insert(materialCatalog).values({ id: uuid(), companyId: params.companyId, materialCode: params.materialCode, materialName: params.materialName, categoryId: params.categoryId||null, uomId: params.uomId||null, description: params.description||null, standardRate: params.standardRate??null }).returning().get(); } };
export const equipmentTypeService = { create(params: { companyId: string; typeCode: string; typeName: string; category?: string; defaultUomId?: string; fuelType?: string }) { return db.insert(equipmentTypes).values({ id: uuid(), companyId: params.companyId, typeCode: params.typeCode, typeName: params.typeName, category: params.category||null, defaultUomId: params.defaultUomId||null, fuelType: params.fuelType||null }).returning().get(); } };
export const skillCatalogService = { create(params: { companyId: string; skillCode: string; skillName: string; trade?: string; category?: string }) { return db.insert(skillCatalog).values({ id: uuid(), companyId: params.companyId, skillCode: params.skillCode, skillName: params.skillName, trade: params.trade||null, category: params.category||null }).returning().get(); } };
